FROM python:3.11-slim

WORKDIR /app

COPY App/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --timeout=120 --retries=10 -r requirements.txt

COPY App/streamlit_app.py /app/streamlit_app.py

EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
